  # Official framework image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
    npm_config_cache: "$CI_PROJECT_DIR/.npm"

  # This folder is cached between builds
  # http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
      - node_modules/
      - .npm

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script:
      - npm ci

#unit testen
test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - npm ci
    - ng test --progress false --watch false
    - npm install karma-junit-reporter
    - karma start --reporters junit
  artifacts:
    reports:
      junit: testReports/report.xml
  tags:
    - docker

#end - 2 - end testen
test:e2e:
  stage: test
  image: trion/ng-cli-e2e:latest
  allow_failure: false
  script:
  - ng e2e
  tags:
  - docker  

#code coverage for code quality
test:code-coverage:
  stage: test
  image: trion/ng-cli-karma:latest
  allow_failure: false
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - docker

#Angular linter for code smells
test:nglint:
  stage: test
  image: trion/ng-cli:latest
  script:
  - ng lint
  tags:
  - docker

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
    - dist
  tags:
    - docker



