# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#       - node_modules/
#       - .npm
#       - cache/Cypress
   
stages:
  - setup
  # - analyse
  - test
  - report
  - build
  - docker

setup:
  image: cypress/base:latest
  stage: setup
  script:
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
    - npx cypress verify
    - npx cypress info

# #SonarQube: Can only scan one branche when using free version
# analyse:sonar:
#   stage: analyse
#   image:
#     name: sonarsource/sonar-scanner-cli:latest
#     entrypoint: [""]
#   variables:
#     # Defines the location of the analysis task cache
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#     # Shallow cloning needs to be disabled.
#     # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
#     GIT_DEPTH: 0
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - sonar-scanner
#   rules:
#     # SonarQube CommunityEdition only supports analyzing a single branch.
#     # So only run on master.
#     - if: '$CI_COMMIT_BRANCH == "master"'
#       when: on_success
#     - when: never


# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml


#unit testen
test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - npm ci
    # - npm install karma-junit-reporter
    # - npm install karma-cli
    - ng test --progress false --watch false
    # - karma start --reporters junit
  artifacts:
    reports:
      junit: $CI_PROJECT_DIR/artifacts/report.xml
  tags:
    - docker

#end - 2 - end testen
test:e2e:
  stage: test
  image: cypress/base:latest
  allow_failure: false
  script:
  - ./node_modules/@angular/cli/bin/ng e2e --progress false --watch false --headless
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/cypress/videos/**/*.mp4
      - $CI_PROJECT_DIR/cypress/screenshots/**/*.png
    expire_in: 1 day
  tags:
  - docker  

#code coverage for code quality
test:code-coverage:
  stage: report
  image: trion/ng-cli-karma:latest
  allow_failure: false
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - $CI_PROJECT_DIR/artifacts/app/coverage/
  tags:
    - docker

#Angular linter for code smells
test:nglint:
  stage: report
  image: trion/ng-cli:latest
  script:
  - ng lint
  tags:
  - docker

#Linter for code smells, bugs and quality 
lint:sonar:
  stage: report
  image: trion/ng-cli:latest
  script:
  - npm install -g sonarqube-scanner
  - >
    sonar-scanner
    -Dsonar.projectKey=test-app
    -Dsonar.host.url=http://localhost:9000
    -Dsonar.login=admin
    -Dsonar.password=Wolfpower123!
    -Dsonar.projectName=test-app
    -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
    -Dsonar.sourceEncoding=UTF-8
    -Dsonar.sources=src/app
    -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
    -Dsonar.tests=src/app
    -Dsonar.test.inclusions=**/*.spec.ts

build:
  stage: build
  image: trion/ng-cli
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer --progress=false
  artifacts:
    paths:
    - dist
  tags:
    - docker

#Pushes this project to the container registry from GitLab inside a container
docker-job:
  stage: docker
  image: docker:dind
  script:
    - echo $CI_REGISTRY_USER; echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/mfwicdaboii/angulargitlabdemo .
    - docker push registry.gitlab.com/mfwicdaboii/angulargitlabdemo



